# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ buildGoPackage, fetchgit, pkgconfig, libxml2 }:

buildGoPackage {
  name = "contrail-introspect-cli-unstable";

  goPackagePath = "github.com/nlewo/contrail-introspect-cli";

  buildInputs = [ pkgconfig libxml2 ];

  src = ./.;
  goDeps = ./deps.nix;
}
