# This file was PARTIALLY generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, libxml2, pkgconfig }:

buildGoPackage rec {
  name = "contrail-introspect-cli-${version}";
  version = "2016-12-09";
  rev = "a7172d4a2bc270c8c56c80c441e2aa3b8fe0a0d5";

  buildInputs = [ libxml2 pkgconfig ];

  goPackagePath = "github.com/nlewo/contrail-introspect-cli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/nlewo/contrail-introspect-cli.git";
    sha256 = "13ibzmxy0vf19nf6gggid5msv1gv7kwjwil8bszshayq66f08r23";
  };

  goDeps = ./deps.nix;
}
